[package]
name = "reqlite-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
iced = { version = "0.14.0", features = ["advanced", "tokio"] }
notify = "8.2.0"
reqlite-engine = { version = "0.0.1", path = "../engine" }
reqlite-format = { version = "0.0.1", path = "../format" }
reqlite-import = { version = "0.0.1", path = "../import" }
reqlite-store = { version = "0.0.1", path = "../store" }
reqlite-viewer = { version = "0.0.1", path = "../viewer" }
reqwest = { version = "0.13.5", default-features = false, features = ["query", "rustls"] }
rfd = "0.17.2"
tokio = { version = "1.53.1", features = ["rt"] }

[lints]
workspace = true

[dev-dependencies]
iced_test = "0.14.0"
tempfile = "3.27.0"
