[package]
name = "reqlite-import"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
reqlite-format = { version = "0.0.1", path = "../format" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.21"

[lints]
workspace = true
